/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shilo' at '19/11/18 1:46 PM' with Gradle 2.14.1
 *
 * @author shilo, @date 19/11/18 1:46 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
